'use client'

import { useMemo, useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { BookOpen, Brain, ChevronRight, Cross, Headphones, Heart, Home, Library, Menu, MessageCircle, Moon, Pause, Play, Search, Send, Sparkles, Sun, Users, Volume2, X } from 'lucide-react'
import { fallbackResponse, parallelPassages, perspectives, plans, prayerSeed, studies } from '@/lib/local-database'

type View = 'inicio' | 'biblia' | 'ia' | 'estudio' | 'planes' | 'comunidad'

const navItems: { id: View; label: string; icon: typeof Home }[] = [
  { id: 'inicio', label: 'Inicio', icon: Home },
  { id: 'biblia', label: 'Biblia', icon: BookOpen },
  { id: 'ia', label: 'RevelatiO IA', icon: Sparkles },
  { id: 'estudio', label: 'Estudio', icon: Library },
  { id: 'planes', label: 'Planes', icon: Brain },
  { id: 'comunidad', label: 'Comunidad', icon: Users },
]

export default function RevelatioApp() {
  const [view, setView] = useState<View>('inicio')
  const [dark, setDark] = useState(false)
  const [sanctuary, setSanctuary] = useState(false)
  const [parallel, setParallel] = useState(true)
  const [playing, setPlaying] = useState(false)
  const [selectedPerspective, setSelectedPerspective] = useState('Teológica')
  const [question, setQuestion] = useState('')
  const [answered, setAnswered] = useState(false)
  const [prayers, setPrayers] = useState(prayerSeed)
  const [prayer, setPrayer] = useState('')
  const [selectedStudy, setSelectedStudy] = useState<number | null>(null)

  const answer = useMemo(() => fallbackResponse(selectedPerspective, 'Romanos 12:2'), [selectedPerspective])
  const ask = () => { if (question.trim()) setAnswered(true) }
  const addPrayer = () => { if (!prayer.trim()) return; setPrayers([{ id: Date.now(), category: 'General', text: prayer, prayers: 0 }, ...prayers]); setPrayer('') }

  return <div className={dark ? 'revelatio-app dark-mode' : 'revelatio-app'}>
    {!sanctuary && <aside className="revelatio-sidebar">
      <div className="revelatio-brand"><div className="brand-symbol"><Cross size={18} /></div><div><strong>RevelatiO</strong><span>BY EFATA</span></div></div>
      <p className="sidebar-label">TU CAMINO</p>
      <nav>{navItems.map(({ id, label, icon: Icon }) => <button key={id} className={view === id ? 'revelatio-nav active' : 'revelatio-nav'} onClick={() => setView(id)}><Icon size={18} /><span>{label}</span>{id === 'ia' && <Sparkles size={12} className="nav-spark" />}</button>)}</nav>
      <div className="sidebar-bottom"><div className="streak"><span className="streak-fire">7</span><div><strong>Racha de estudio</strong><small>7 días consecutivos</small></div></div><button className="revelatio-nav"><Heart size={18} /><span>Favoritos</span></button><a className="creator-credit" href="https://www.xtrametrik.com" target="_blank" rel="noreferrer">Tecnología ética por XtraMetrik</a></div>
    </aside>}
    <main className="revelatio-main">
      <header className="revelatio-header"><button className="mobile-menu" aria-label="Abrir menú"><Menu size={20} /></button><div><p className="kicker">{sanctuary ? 'MODO SANTUARIO' : 'ROMANOS 12:2 · NBLA'}</p><h1>{sanctuary ? 'Quédate aquí un momento.' : view === 'inicio' ? 'Buenos días, caminante.' : navItems.find(item => item.id === view)?.label}</h1></div><div className="header-actions"><button className="icon-btn" onClick={() => setDark(!dark)} aria-label="Cambiar tema">{dark ? <Sun size={18} /> : <Moon size={18} />}</button><div className="avatar-user">AS</div></div></header>
      <div className="revelatio-content">
        <AnimatePresence mode="wait">{view === 'inicio' && <motion.div key="home" className="view-stack" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}>
          <section className="welcome-hero"><div><p className="kicker gold">TU MOMENTO DE HOY</p><h2>Una mente renovada<br /><em>comienza aquí.</em></h2><p>Un espacio para leer la Palabra, comprenderla profundamente y dejar que transforme tu manera de vivir.</p><button className="gold-btn" onClick={() => setView('biblia')}>Continuar mi camino <ChevronRight size={16} /></button></div><div className="hero-verse"><span>“</span><blockquote>No os conforméis a este siglo, sino transformaos por medio de la renovación de vuestro entendimiento.</blockquote><small>ROMANOS 12:2 · NBLA</small></div></section>
          <div className="section-heading"><div><p className="kicker">TU RITMO</p><h2>Continúa donde lo dejaste</h2></div><button className="text-btn" onClick={() => setView('estudio')}>Ver todo <ChevronRight size={14} /></button></div>
          <div className="continue-grid"><button className="continue-card" onClick={() => setView('biblia')}><div className="card-icon blue"><BookOpen size={20} /></div><div><span>BIBLIA · ROMANOS 12</span><strong>La mente que Dios quiere renovar</strong><small>Capítulo 12 · 68% completado</small></div><ChevronRight size={17} /></button><button className="continue-card" onClick={() => setView('estudio')}><div className="card-icon gold-icon"><Sparkles size={20} /></div><div><span>ESTUDIO · BLOQUE 1</span><strong>El carácter de Dios</strong><small>Sesión 3 de 6 · 12 min restantes</small></div><ChevronRight size={17} /></button></div>
          <div className="dashboard-grid"><section className="quote-card"><p className="kicker gold">PALABRA PARA HOY</p><p className="scripture">“Encomienda a Jehová tus obras,<br />y tus pensamientos serán afirmados.”</p><small>PROVERBIOS 16:3 · RVR1960</small><button className="audio-link" onClick={() => setPlaying(!playing)}>{playing ? <Pause size={14} /> : <Play size={14} />} {playing ? 'Pausar lectura' : 'Escuchar pasaje'}</button></section><section className="progress-card"><p className="kicker">ESTA SEMANA</p><div className="progress-number">4 <small>/ 7 días</small></div><div className="progress-track"><span style={{ width: '57%' }} /></div><p>Tu constancia está formando algo más profundo que un hábito.</p><button className="text-btn" onClick={() => setView('planes')}>Ver mi progreso <ChevronRight size={14} /></button></section></div>
        </motion.div>}
        {view === 'biblia' && <motion.div key="bible" className="view-stack" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><div className="page-toolbar"><div><p className="kicker gold">LECTURA PROFUNDA</p><h2>Romanos 12</h2></div><div className="toolbar-actions"><button className={sanctuary ? 'pill-btn selected' : 'pill-btn'} onClick={() => setSanctuary(true)}><Headphones size={15} /> Modo Santuario</button><button className={parallel ? 'pill-btn selected' : 'pill-btn'} onClick={() => setParallel(!parallel)}><Library size={15} /> Paralelo</button></div></div><div className="bible-search"><Search size={17} /><input placeholder="Buscar una referencia, palabra o tema..." defaultValue="Romanos 12:2" /><button className="gold-btn small">Ir</button></div><div className={parallel ? 'parallel-grid' : 'parallel-grid single'}>{(parallel ? parallelPassages : [parallelPassages[0]]).map((passage) => <article className="version-card" key={passage.version}><div className="version-label"><span>{passage.version}</span><button aria-label="Escuchar versión"><Volume2 size={15} /></button></div><p>{passage.text}</p><small>ROMANOS 12:2</small></article>)}</div><section className="commentary-card"><div className="commentary-header"><div><p className="kicker gold">COMENTARIO HISTÓRICO</p><h3>La transformación comienza en la mente</h3></div><span className="author-chip">Matthew Henry</span></div><p>La voluntad de Dios no se descubre desde una vida conformada, sino cuando permitimos que la verdad reordene nuestros afectos y decisiones. El texto no propone una huida del mundo, sino una nueva manera de habitarlo.</p><blockquote>“La mente renovada discierne lo bueno porque ha aprendido a amar lo que Dios ama.”</blockquote></section></motion.div>}
        {view === 'ia' && <motion.div key="ai" className="view-stack ai-view" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><div className="ai-heading"><div className="ai-orb"><Sparkles size={24} /></div><div><p className="kicker gold">REVELATIO IA</p><h2>Pregunta con profundidad.</h2><p>Un acompañamiento para estudiar la Palabra con rigor, contexto y corazón.</p></div></div><div className="context-card"><BookOpen size={16} /><div><small>VERSÍCULO EN ANÁLISIS</small><strong>Romanos 12:2 · NBLA</strong></div><button onClick={() => setQuestion('')} aria-label="Quitar contexto"><X size={15} /></button></div><div className="perspective-row">{perspectives.map(p => <button key={p.name} className={selectedPerspective === p.name ? 'perspective active' : 'perspective'} onClick={() => { setSelectedPerspective(p.name); setAnswered(true) }}>{p.name}</button>)}</div><div className="question-box"><textarea value={question} onChange={e => setQuestion(e.target.value)} placeholder="¿Qué quieres comprender hoy?" /><button className="send-btn" onClick={ask} aria-label="Preguntar"><Send size={17} /></button></div>{answered && <motion.div className="answer-card" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}><div className="answer-top"><Sparkles size={16} /><span>Perspectiva {selectedPerspective}</span></div><div className="answer-sections"><div><small>CONTEXTO</small><p>{answer.context}</p></div><div><small>ANÁLISIS TÉCNICO</small><p>{answer.analysis}</p></div><div><small>CONEXIÓN PRÁCTICA</small><p>{answer.practice}</p></div><div><small>CONCLUSIÓN</small><p>{answer.conclusion}</p></div></div></motion.div>}</motion.div>}
        {view === 'estudio' && <motion.div key="study" className="view-stack" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><div className="page-toolbar"><div><p className="kicker gold">FORMACIÓN</p><h2>Estudios profundos</h2><p className="muted">20 rutas para pasar del texto a tu corazón.</p></div><div className="study-count">20 <span>estudios</span></div></div>{selectedStudy ? <StudyCanvas study={studies.find(s => s.id === selectedStudy)!} onBack={() => setSelectedStudy(null)} /> : <div className="study-grid">{studies.slice(0, 8).map(study => <button className="study-card" key={study.id} onClick={() => setSelectedStudy(study.id)}><span className="study-block">{study.block}</span><strong>{study.title}</strong><small>{study.verse} · {study.duration}</small><ChevronRight size={16} /></button>)}</div>}</motion.div>}
        {view === 'planes' && <motion.div key="plans" className="view-stack" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><div className="page-toolbar"><div><p className="kicker gold">CONSTANCIA</p><h2>Planes de lectura</h2><p className="muted">La fidelidad se construye un día a la vez.</p></div></div><div className="plans-grid">{plans.map(plan => <article className="plan-card" key={plan.title}><div className="plan-cover"><BookOpen size={25} /></div><p className="kicker gold">{plan.days} DÍAS</p><h3>{plan.title}</h3><p>{plan.detail}</p><div className="progress-track"><span style={{ width: `${plan.progress}%` }} /></div><small>{plan.progress}% completado</small><button className="gold-btn small">Continuar <ChevronRight size={14} /></button></article>)}</div></motion.div>}
        {view === 'comunidad' && <motion.div key="community" className="view-stack" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><div className="page-toolbar"><div><p className="kicker gold">CAMINAMOS JUNTOS</p><h2>Comunidad</h2><p className="muted">Lleva las cargas de otros, y así cumplirás la ley de Cristo.</p></div></div><section className="prayer-composer"><Heart size={19} /><input value={prayer} onChange={e => setPrayer(e.target.value)} placeholder="Comparte una petición de oración..." /><button className="gold-btn small" onClick={addPrayer}>Publicar</button></section><div className="prayer-list">{prayers.map(item => <article className="prayer-card" key={item.id}><span className="prayer-category">{item.category}</span><p>{item.text}</p><button onClick={() => setPrayers(prayers.map(p => p.id === item.id ? { ...p, prayers: p.prayers + 1 } : p))}><Heart size={15} /> Estoy orando por ti · {item.prayers}</button></article>)}</div></motion.div>}
        </AnimatePresence>
      </div>
    </main>
    {sanctuary && <div className="sanctuary-player"><div className="sanctuary-ambient"><div className="sound-wave"><i /><i /><i /><i /><i /></div><div><p className="kicker gold">AMBIENTE DEL SANTUARIO</p><strong>Shalom · Instrumental</strong><small>Reproducción local sin conexión</small></div></div><div className="player-controls"><button onClick={() => setPlaying(!playing)} aria-label={playing ? 'Pausar' : 'Reproducir'}>{playing ? <Pause /> : <Play />}</button><input type="range" min="0" max="100" defaultValue="62" aria-label="Volumen" /><Volume2 size={17} /><button className="close-sanctuary" onClick={() => setSanctuary(false)}><X size={18} /> Salir</button></div></div>}
  </div>
}

function StudyCanvas({ study, onBack }: { study: { title: string; verse: string }; onBack: () => void }) { return <section className="study-canvas"><button className="text-btn" onClick={onBack}>← Volver a estudios</button><div className="canvas-header"><span className="study-number">01</span><div><p className="kicker gold">RUTA DE ESTUDIO</p><h3>{study.title}</h3><p>{study.verse} · Paso 1 de 6</p></div></div><div className="steps-row">{['Devocional', 'Exégesis', 'Cirugía del corazón', 'Quiz', 'Anclaje', 'Conclusión'].map((step, i) => <div className={i === 0 ? 'canvas-step active' : 'canvas-step'} key={step}><span>{i + 1}</span>{step}</div>)}</div><article className="devotional-block"><p className="kicker gold">DEVOCIONAL</p><h4>La Palabra no solo informa; transforma.</h4><p>Antes de analizar, permite que el texto te encuentre. Lee Romanos 12:2 lentamente. ¿Qué parte de tu manera de pensar necesita ser presentada hoy delante de Dios?</p><textarea placeholder="Escribe tu reflexión..." /><button className="gold-btn">Guardar reflexión <ChevronRight size={16} /></button></article></section> }
