/* Catálogo local de Discipulado. No llama a IA ni consume créditos. */
const DISCIPULADO_CATALOGO = {
  version: 1,
  titulo: 'Ruta de discipulado integral',
  introduccion: 'Un camino bíblico para pasar de la convicción a una fe firme, obediente y compartida.',
  fases: [
    { id: 'enraizamiento', numero: 1, titulo: 'Caminar en la luz', descripcion: 'Confesión, arrepentimiento y una conciencia abierta delante de Dios.', hito: '1 Juan 1:9 · Si confesamos nuestros pecados, Él es fiel y justo para perdonarnos.', modulos: ['conviccion', 'arrepentimiento'] },
    { id: 'palabra', numero: 2, titulo: 'Alimentarse de la Palabra', descripcion: 'Leer el texto en contexto y responder a la verdad recibida.', hito: '1 Pedro 2:2 · Deseen la leche pura de la palabra, para que por ella crezcan.', modulos: ['palabra'] },
    { id: 'caracter', numero: 3, titulo: 'Obedecer en comunidad', descripcion: 'Convertir la verdad bíblica en hábitos, servicio y rendición de cuentas.', hito: 'Santiago 1:22 · Sean hacedores de la palabra y no solamente oidores.', modulos: ['comunidad'] },
    { id: 'firmeza', numero: 4, titulo: 'Permanecer firmes', descripcion: 'Vivir sólidos y constantes, incluso cuando el fruto no sea inmediato.', hito: '1 Corintios 15:58 · Estén firmes, constantes, abundando siempre en la obra del Señor.', modulos: ['perseverancia'] }
  ],
  modulos: [
    { id: 'conviccion', faseId: 'enraizamiento', titulo: 'Convicción y confesión', lecciones: ['luz-01'] },
    { id: 'arrepentimiento', faseId: 'enraizamiento', titulo: 'Arrepentimiento real', lecciones: ['luz-02'] },
    { id: 'palabra', faseId: 'palabra', titulo: 'Lectura obediente', lecciones: ['palabra-01'] },
    { id: 'comunidad', faseId: 'caracter', titulo: 'Fe que se practica con otros', lecciones: ['comunidad-01'] },
    { id: 'perseverancia', faseId: 'firmeza', titulo: 'Constancia y esperanza', lecciones: ['firmeza-01'] }
  ],
  lecciones: [
    { id: 'luz-01', moduloId: 'conviccion', titulo: 'Volver a la verdad', duracion: '15 minutos', objetivo: 'Reconocer delante de Dios aquello que necesita ser rendido.', lectura: 'La confesión cristiana no es esconderse ni justificarse. Es volver a la verdad delante de Dios y descansar en su fidelidad. El discípulo comienza dejando de negociar con aquello que necesita ser rendido.', referencias: [{ ref: '1 Juan 1:9', texto: 'Si confesamos nuestros pecados, Él es fiel y justo para perdonarnos los pecados y para limpiarnos de toda maldad.' }], tresM: { atras: '¿Qué necesitas revisar con honestidad?', arriba: 'Lee 1 Juan 1:9 lentamente y ora sin justificarte.', adelante: 'Da un paso concreto de reconciliación o restitución.' }, aplicacion: 'Escribe una confesión concreta y preséntala a Dios en oración.', pregunta: '¿Qué respuesta pide hoy la fidelidad de Dios?' },
    { id: 'luz-02', moduloId: 'arrepentimiento', titulo: 'Una conciencia limpia', duracion: '15 minutos', objetivo: 'Distinguir arrepentimiento bíblico de remordimiento sin cambio.', lectura: 'Dios no examina para destruir, sino para conducir a la vida. El arrepentimiento cambia dirección: recibe corrección, abandona el autoengaño y busca caminar acompañado.', referencias: [{ ref: 'Salmo 139:23-24', texto: 'Examíname, oh Dios, y conoce mi corazón; pruébame y conoce mis inquietudes.' }], tresM: { atras: '¿Qué patrón se repitió esta semana?', arriba: 'Permite que Dios examine tus caminos.', adelante: 'Comparte un próximo paso con alguien maduro.' }, aplicacion: 'Identifica una decisión que necesita alinearse con la verdad bíblica.', pregunta: '¿Qué cambio visible mostraría un arrepentimiento genuino?' },
    { id: 'palabra-01', moduloId: 'palabra', titulo: 'Hambre de la Palabra', duracion: '20 minutos', objetivo: 'Aprender a observar, interpretar y aplicar el texto bíblico.', lectura: 'La Palabra no es un adorno espiritual ni una lista de datos. Es alimento para una vida que está creciendo. Lee despacio: observa quién habla, qué revela el texto y qué obediencia pide hoy.', referencias: [{ ref: '1 Pedro 2:2', texto: 'Deseen como niños recién nacidos la leche pura de la palabra, para que por ella crezcan para salvación.' }], tresM: { atras: '¿Qué hábito de lectura pudiste sostener?', arriba: 'Observa qué produce el deseo por la Palabra.', adelante: 'Agenda tu próxima lectura y compártela.' }, aplicacion: 'Anota una verdad, una corrección y una obediencia para esta semana.', pregunta: '¿Qué parte del texto has leído sin permitir que te lea a ti?' },
    { id: 'comunidad-01', moduloId: 'comunidad', titulo: 'Oidores y hacedores', duracion: '20 minutos', objetivo: 'Practicar la verdad con humildad, gracia y rendición de cuentas.', lectura: 'La escucha bíblica alcanza su propósito cuando se convierte en obediencia. La comunidad no es un tribunal; es el lugar donde aprendemos a practicar la verdad con humildad y gracia.', referencias: [{ ref: 'Santiago 1:22', texto: 'Sean hacedores de la palabra y no solamente oidores que se engañan a sí mismos.' }], tresM: { atras: '¿Qué compromiso compartido cumpliste?', arriba: 'Compara el texto con tu práctica.', adelante: 'Pide rendición de cuentas sobre una obediencia concreta.' }, aplicacion: 'Comparte con una persona madura qué obediencia practicarás esta semana.', pregunta: '¿Dónde necesitas dejar de escuchar y comenzar a obedecer?' },
    { id: 'firmeza-01', moduloId: 'perseverancia', titulo: 'Firmes y constantes', duracion: '15 minutos', objetivo: 'Permanecer orientado por la esperanza de Cristo.', lectura: 'La firmeza cristiana no significa ausencia de cansancio. Significa permanecer orientado por la esperanza de Cristo y seguir sirviendo aunque el fruto no sea inmediato.', referencias: [{ ref: '1 Corintios 15:58', texto: 'Estén firmes, constantes, abundando siempre en la obra del Señor.' }], tresM: { atras: '¿Dónde viste fidelidad en medio de la dificultad?', arriba: 'Medita en la esperanza de la resurrección.', adelante: 'Elige una forma concreta de servir con constancia.' }, aplicacion: 'Define un servicio concreto y una forma de mantenerte constante.', pregunta: '¿Qué te ayudará a permanecer cuando no veas resultados?' }
  ]
};
window.DISCIPULADO_CATALOGO = DISCIPULADO_CATALOGO;
