window.ESTUDIOS_MAESTRO = {
  categories: [
    {id:1,title:'Doctrina',slug:'doctrina',description:'Las verdades centrales de la fe cristiana.'},
    {id:2,title:'Hermenéutica',slug:'hermeneutica',description:'Leer, interpretar y aplicar fielmente el texto.'},
    {id:3,title:'Antropología bíblica',slug:'antropologia',description:'La persona humana ante Dios, el pecado y la redención.'},
    {id:4,title:'Personajes bíblicos',slug:'personajes',description:'Vidas reales leídas dentro de la historia de la redención.'},
    {id:5,title:'Teología práctica',slug:'practica',description:'La Palabra formando decisiones, hábitos y comunidad.'},
    {id:6,title:'Sanidad emocional',slug:'sanidad',description:'Dolor, esperanza y restauración bajo la verdad bíblica.'}
  ],
  studies: [
    {slug:'romanos-122',category:'doctrina',title:'La mente renovada',subtitle:'Discernir la voluntad de Dios sin conformarse al siglo',passage:'Romanos 12:1-2',context:'Pablo escribe a una iglesia mixta en Roma, situada entre presiones imperiales, idolatría pública y tensiones entre judíos y gentiles.',linguistic:'La palabra μεταμορφόω (G3339) describe una transformación real de la forma; νοῦς (G3563) apunta a la mente como centro del discernimiento moral.',theology:'La respuesta cristiana nace de las misericordias de Dios: la consagración no compra la salvación, la expresa. Creación, caída, redención y consumación convergen en una vida ofrecida.',bridge:'El texto no enseña aislamiento cultural, sino una obediencia capaz de discernir dentro de la cultura sin rendirse a sus ídolos.',authors:['Matthew Henry: la renovación interior produce una vida que ya no pertenece al molde del mundo.','J.C. Ryle: la santidad verdadera alcanza pensamientos, afectos y decisiones.'],questions:['¿Qué patrón de este siglo está formando tus deseos?','¿Qué decisión concreta demostraría una mente renovada?'],words:[{word:'metamorfóō',strong:'G3339',meaning:'transformar, cambiar de forma'}]},
    {slug:'genesis-1-imagen',category:'antropologia',title:'Imagen de Dios',subtitle:'Dignidad, vocación y responsabilidad humana',passage:'Génesis 1:26-28',context:'El relato polemiza con los mitos del antiguo Cercano Oriente: no solo el rey, sino cada ser humano recibe dignidad ante el Creador.',linguistic:'צֶלֶם (H6754) comunica imagen o representación; דְּמוּת (H1823) señala semejanza. El mandato de gobernar está unido a reflejar al Rey.',theology:'La imagen permanece marcada por la caída, es restaurada en Cristo y será plenamente manifestada en la consumación.',bridge:'La dignidad bíblica impide tanto reducir a la persona a productividad como convertir la autonomía en idolatría.',authors:['Juan Calvino: la imagen se contempla en la justicia, santidad y conocimiento restaurados.'],questions:['¿A quién estás tratando como medio y no como portador de la imagen?','¿Cómo ejercerás autoridad como servicio?'],words:[{word:'tselem',strong:'H6754',meaning:'imagen, representación'}]},
    {slug:'salmo-23-pastor',category:'sanidad',title:'El Señor es mi pastor',subtitle:'Presencia, provisión y esperanza en el valle',passage:'Salmo 23',context:'El salmo usa imágenes pastoriles conocidas por Israel: guía, agua, mesa, aceite y protección en territorio peligroso.',linguistic:'רֹעִי (H7462) es mi pastor; חסד (H2617) expresa amor leal de pacto, no una emoción pasajera.',theology:'Dios no promete ausencia de valle, sino su presencia allí. El Rey-pastor conduce hacia comunión y habitación permanente.',bridge:'La ansiedad no se resuelve negando el peligro; se enfrenta nombrando quién guía, sostiene y acompaña.',authors:['Charles Spurgeon: la presencia del Pastor convierte el valle en camino y no en destino.'],questions:['¿Qué temor está interpretando hoy el carácter de Dios?','¿Qué provisión presente has dejado de reconocer?'],words:[{word:'hesed',strong:'H2617',meaning:'amor leal, misericordia de pacto'}]},
    {slug:'marcos-10-siervo',category:'practica',title:'La grandeza del siervo',subtitle:'Autoridad invertida por el modelo de Jesús',passage:'Marcos 10:35-45',context:'Los discípulos esperan posiciones de honor; Jesús responde en un mundo donde rango, patronazgo y prestigio definían las relaciones.',linguistic:'διακονέω (G1247) significa servir; λύτρον (G3083) es rescate. La autoridad se interpreta desde la entrega del Hijo.',theology:'El Hijo del Hombre cumple Isaías 53: su reino no reproduce la dominación de las naciones, sino que redime mediante sacrificio.',bridge:'Liderar cristianamente significa asumir responsabilidad por el bien del otro, no usar personas para validar el ego.',authors:['Martyn Lloyd-Jones: el orgullo busca posición; Cristo forma siervos que descienden para levantar.'],questions:['¿Qué reconocimiento estás buscando?','¿Qué acto de servicio no visible practicarás esta semana?'],words:[{word:'diakoneō',strong:'G1247',meaning:'servir, atender las necesidades'}]},
    {slug:'efesios-2-gracia',category:'doctrina',title:'Salvados por gracia',subtitle:'De muerte espiritual a una vida preparada por Dios',passage:'Efesios 2:1-10',context:'Pablo contrasta la vida bajo poderes, deseos y estructuras del mundo con la nueva humanidad creada en Cristo.',linguistic:'χάρις (G5485) es gracia favorable; ποίημα (G4161) indica obra o hechura. Las buenas obras son fruto, no fundamento.',theology:'La salvación es iniciativa misericordiosa de Dios, unión con Cristo y creación de una vida nueva para buenas obras.',bridge:'La gracia destruye la jactancia y también la pasividad: quien ha sido creado en Cristo camina en obediencia.',authors:['Matthew Henry: la gracia no solo rescata del pasado; prepara una senda de obediencia.'],questions:['¿Dónde intentas presentarte justo por rendimiento?','¿Qué buena obra preparada por Dios estás evitando?'],words:[{word:'charis',strong:'G5485',meaning:'gracia, favor inmerecido'}]},
    {slug:'santiago-1-palabra',category:'hermeneutica',title:'Oidores y hacedores',subtitle:'La Palabra recibida con mansedumbre',passage:'Santiago 1:19-27',context:'Santiago escribe a comunidades dispersas bajo presión, donde la religión podía reducirse a discurso sin dominio de la lengua ni cuidado del vulnerable.',linguistic:'ποιητής (G4163) es hacedor; θρησκεία (G2356) describe la práctica religiosa visible. El espejo revela, pero exige respuesta.',theology:'La Palabra implantada salva y forma una religión pura: dominio propio, misericordia y separación de la corrupción.',bridge:'Interpretar bien culmina en una práctica verificable, especialmente en cómo hablamos y cómo tratamos al débil.',authors:['J.C. Ryle: la fe que no afecta la conducta es una profesión sin evidencia.'],questions:['¿Qué verdad escuchas repetidamente sin obedecer?','¿Quién vulnerable necesita tu cuidado concreto?'],words:[{word:'poiētēs',strong:'G4163',meaning:'hacedor, quien practica'}]},
    {slug:'lucas-15-padre',category:'personajes',title:'El Padre que recibe',subtitle:'Arrepentimiento, gracia y restauración',passage:'Lucas 15:11-32',context:'Jesús responde a la murmuración religiosa contando una historia sobre honor familiar, herencia, vergüenza pública y restauración en una aldea.',linguistic:'μετανοέω (G3340) implica cambio de mente y dirección; σπλαγχνίζομαι (G4698) describe compasión profunda.',theology:'El Padre sale al encuentro del rebelde y confronta al moralista. La restauración nace de gracia, no de negociación.',bridge:'El arrepentimiento bíblico vuelve al Padre y también abandona la justicia comparativa del hermano mayor.',authors:['Charles Spurgeon: ambos hijos necesitan la gracia, uno por rebelión visible y otro por orgullo religioso.'],questions:['¿Te ves más en la fuga o en la comparación?','¿A quién debes recibir sin negar la verdad?'],words:[{word:'metanoeō',strong:'G3340',meaning:'arrepentirse, cambiar de mente'}]},
    {slug:'juan-15-permanecer',category:'practica',title:'Permanecer en Cristo',subtitle:'Fruto, poda y dependencia',passage:'Juan 15:1-11',context:'En el discurso de despedida, Jesús prepara a sus discípulos para una presencia que no dependerá de su visibilidad física.',linguistic:'μένω (G3306) significa permanecer, habitar, continuar. El imperativo describe relación sostenida, no una visita ocasional.',theology:'La vida fructífera procede de unión con Cristo; la poda del Padre es disciplina orientada al fruto y al gozo.',bridge:'Permanecer se concreta en palabra, oración, obediencia y amor comunitario, no en una sensación espiritual permanente.',authors:['John Owen: la comunión con Cristo alimenta cada acto de santidad.'],questions:['¿Qué práctica está desconectada de la vid?','¿Qué poda estás interpretando como abandono?'],words:[{word:'menō',strong:'G3306',meaning:'permanecer, habitar'}]}
  ]
};
window.ESTUDIOS_MAESTRO.studies = window.ESTUDIOS_MAESTRO.studies.map((study,index) => ({...study, number:index+1}));
window.ESTUDIO_CATEGORIAS = window.ESTUDIOS_MAESTRO.categories;
window.ESTUDIO_CATALOGO = window.ESTUDIOS_MAESTRO.studies; 
function buscarEstudiosMaestro(query, category) { const q=(query||'').trim().toLocaleLowerCase('es'); return window.ESTUDIO_CATALOGO.filter(s => (!category || s.category===category) && (!q || [s.title,s.subtitle,s.passage,s.context,s.theology,s.bridge].join(' ').toLocaleLowerCase('es').includes(q))); }
function guardarEstudioNota(slug, notes) { try { const all=JSON.parse(localStorage.getItem('revelatio-estudio-notas-v1')||'{}'); all[slug]=notes; localStorage.setItem('revelatio-estudio-notas-v1',JSON.stringify(all)); } catch(e) {} }
function cargarEstudioNota(slug) { try { return JSON.parse(localStorage.getItem('revelatio-estudio-notas-v1')||'{}')[slug]||''; } catch(e) { return ''; } }
function guardarEstudioMarcador(slug) { try { const all=JSON.parse(localStorage.getItem('revelatio-estudio-marcadores-v1')||'[]'); if(!all.includes(slug)) all.push(slug); localStorage.setItem('revelatio-estudio-marcadores-v1',JSON.stringify(all)); return all; } catch(e) { return []; } } 
function cargarEstudioMarcadores() { try { return JSON.parse(localStorage.getItem('revelatio-estudio-marcadores-v1')||'[]'); } catch(e) { return []; } }
function cargarEstudiosActivos() { try { return JSON.parse(localStorage.getItem('revelatio-estudios-activos-v1')||'[]'); } catch(e) { return []; } }
function guardarEstudiosActivos(slugs) { try { localStorage.setItem('revelatio-estudios-activos-v1', JSON.stringify(slugs)); } catch(e) {} return slugs; }
